namespace: default
nameOverride: backend
deploymentName: backend-chart-deployment

replicaCount: 1
image:
  repository: miguelfeo/kubernetesback
  pullPolicy: Always
  tag: "1.2"

service:
  type: ClusterIP
  port: 8087

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  hosts:
    - host: ""
      paths:
        - path: /backend
          pathType: Prefix
  tls: []
